# Generated by Django 6.0.2 on 2026-03-02 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_alter_ingredient_options_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(255)]
            ),
        ),
    ]
